version 0.6-1

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3871,11 +3871,21 @@ to set all Java-related variables and then install rJava.
    { (exit 1); exit 1; }; }
 fi
 
-LIBS="${LIBS} ${JAVA_LIBS}"
-CFLAGS="${CFLAGS} ${JAVA_CPPFLAGS}"
+if test `echo foo | sed -e 's:foo:bar:'` = bar; then
+   JAVA_CPPFLAGS0=`echo ${JAVA_CPPFLAGS} | sed -e 's:$(JAVA_HOME):'${JAVA_HOME}':g'`
+   JAVA_LIBS0=`echo ${JAVA_LIBS} | sed -e 's:$(JAVA_HOME):'${JAVA_HOME}':g'`
+   JAVA_LD_LIBRARY_PATH0=`echo ${JAVA_LD_LIBRARY_PATH} | sed -e 's:$(JAVA_HOME):'${JAVA_HOME}':g'`
+else
+   { echo "$as_me:$LINENO: WARNING: sed is not working properly - the configuration may fail" >&5
+echo "$as_me: WARNING: sed is not working properly - the configuration may fail" >&2;}
+   JAVA_CPPFLAGS0="${JAVA_CPPFLAGS}"
+   JAVA_LIBS0="${JAVA_LIBS}"
+   JAVA_LD_LIBRARY_PATH0="${JAVA_LD_LIBRARY_PATH}"
+fi
 
-SAVE_LDLP="${LD_LIBRARY_PATH}"
-LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${JAVA_LD_LIBRARY_PATH}"
+LIBS="${LIBS} ${JAVA_LIBS0}"
+CFLAGS="${CFLAGS} ${JAVA_CPPFLAGS0}"
+LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${JAVA_LD_LIBRARY_PATH0}"
 
 { echo "$as_me:$LINENO: checking whether JNI programs can be compiled" >&5
 echo $ECHO_N "checking whether JNI programs can be compiled... $ECHO_C" >&6; }
@@ -3992,7 +4002,9 @@ echo $ECHO_N "checking whether JRI should be compiled (autodetect)... $ECHO_C" >
 echo "${ECHO_T}${has_R_shlib}" >&6; }
    want_jri=${has_R_shlib}
 fi
- if test "x${want_jri}" = xyes; then
+
+
+if test "x${want_jri}" = xyes; then
   WANT_JRI_TRUE=
   WANT_JRI_FALSE='#'
 else
